export const epiloqueAz = `
Ey qullarını əzabdan qoruyub qurtaran və əfvi bol olan Rəbbim! Əfvinlə, fəzilətinlə bizi əfv et və bağışla, bizi yaxşı əməl sahibləri ilə bərabər Cənnətinə qoy! Mən bu qiymətli və şərəfli isimlərinin, bu uca və lətif sifətlərinin haqqı üçün Həzrəti Məhəmmədə, Ailəsi və Əshabına, Onun etdiyi yaxşılıqların sayı qədər rəhmət etməni diləyir və bunun üçün yalvarıram!
Allahın adı ilə, Allah mənə kifayət edər, Allahdan başqa ilah yoxdur, Allah hər şeyə şahiddir. De ki, O, Allahdır. Allahın dilədiyi olar. Rəbbim Allahdır. Allahın şanı çox ucadır. Allah uludur. Allaha təvəkkül etdim.
Düşmənlərə qarşı dayaq olaraq Allah sənə yetər. O, hər şeyi eşidən və biləndir.
Ey Allahım, Sən bütün nöqsan və qüsurlardan uzaqsan və bütün gözəlliklərin sahibisən. Səndən başqa həqiqi ilah yoxdur. Aman verən sənsən, Səndən aman diləyirik. Zatını tərif etdiyin kimi, Səni tərif etməkdə aciz olduğumu etiraf edirəm. Ya Allah, Ya Rəhman, Ya Ğafur, Ya Şəkur.
Allahım! Zatın üçün saydığın gözəl isimlərin, uca sifətlərin və mükəmməl kəlimələrin haqqı üçün Səndən istəyir və yalvarıram; məni, anamı, atamı, böyüklərimizi, istər diri, istər ölü olsun — bütün mömin kişi və qadınları, müsəlman kişi və qadınları bağışla.
Ya Rəbb! Bizə elə rəhm et ki, Səndən başqasının mərhəmətinə ehtiyac duymayaq.
Dünya və axirət ehtiyaclarımızı qarşıla və diləklərimizi yerinə yetir.
Ya Rəbb! Bizə etdiyi yaxşılıqlar və üstümüzdəki haqqı üçün bizim adımızdan Həzrəti Məhəmməd sallallahu əleyhi və səlləmi layiq olduğu nemətlərlə mükafatlandır.
Ya Rəbb! Bizi bir göz qırpımı olsa belə, nəfsimizlə baş-başa buraxma. Halımızı islah et, yuxubilməz gözünlə bizi qoru və bizdən ayrılmayan dəstəyinlə bizləri mühafizə et, ey qüdrət və səxavət sahibi Rəbbim!
Ya Rəbb! Bizi və üstündə sənin bu mübarək adlarını daşıyanları cin, insan və şeytanlardan gələn müsibət və bəlalardan, zəlzələlərdən, dağların Allah qorxusu ilə parçalanmasından, taun, vəba, bəd nəzərdən və bədənimizi digər xəstəlik və ağrılar kimi hər cür fəlakət, bəla, müsibət və pisliklərdən qoru!
Ey mərhəmətlilərin ən mərhəmətlisi olan Rəbbim! Sonsuz rəhmətinlə bizə dünya və axirətdə salamatlıq, rahatlıq və xeyir nəsib et! Ya Rəbb! Sultanımız Həzrəti Məhəmmədə, Onun Ailəsinə və bütün səhabələrinə hamısına səlat və salam et!
Aləmlərin Rəbbi olan Allaha həmd olsun!

Tərcümə: Qafar Ocaqlı
`
export const epiloqAr =`
اَللّٰهُمَّ رَبَّنَا ٭ خَلِّصْنَا ٭ وَ اَجِرْنَا ٭ وَ نَجِّنَا مِنَ النَّارِ ٭● وَ عَافِنَا وَ اعْفُ عَنَّا وَ اَدْخِلْنَا الْجَنَّةَ دَارَ قُدْسِكَ مَعَ الْاَبْرَارِ ٭ بِعَفْوِكَ يَا مُجِيرُ ٭ بِفَضْلِكَ يَا غَفَّارُ● وَ اَسْئَلُكَ بِحَقِّ هٰذِهِ الْاَسْمَٓاءِ الْكَر۪يمَةِ الشَّر۪يفَةِ وَ الصِّفَاتِ الْجَلِيلَةِ الَّلطِيفَةِ اَنْ تُصَلِّىَ عَلٰى سَيِّدِنَا مُحَمَّدٍ وَ عَلٰٓى اٰلِهِ وَ صَحْبِهِ بِعَدَدِ حَسَنَاتِ مُحَمَّدٍ بِسْمِ اللّٰهِ ٭ حَسْبِىَ اللّٰهُ ٭ لَٓا اِلٰهَ اِلَّا اللّٰهُ ٭ شَهِدَ اللّٰهُ ٭ قُلْ هُوَ اللّٰهُ ٭ مَا شَٓاءَ اللّٰهُ ٭ رَبِّىَ اللّٰهُ ٭ تَبَارَكَ اللّٰهُ ٭ تَعَالَى اللّٰهُ ٭ تَوَكَّلْتُ عَلَى اللّٰهِ ٭ فَسَيَكْف۪يكَهُمُ اللّٰهُ وَ هُوَ السَّمِيعُ الْعَلِيمُ●سُبْحَانَكَ يَا لَٓا اِلٰهَ اِلَّا ٓ اَنْتَ الْاَمَانَ الْاَمَانَ لَٓا اُحْصِى ثَنَٓاءً عَلَيْكَ اَنْتَ كَمَٓا اَثْنَيْتَ عَلٰى نَفْسِكَ ٭ يَٓا اَللّٰهُ ٭ يَا رَحْمٰنُ ٭ يَا رَحِيمُ ٭ يَا غَفُورُ ٭ يَا شَكُورُ ٭ اَسْئَلُكَ بِمَٓا اَحْصَيْتَهُ عَلَيْكَ مِنْ اَسْمَٓائِكَ الْحُسْنٰى وَ صِفَاتِكَ الْعُلْيَا وَ كَلِمَاتِكَ التَّٓامَّةِ اَنْ تَغْفِرَلِى وَ لِوَالِدَىَّ وَ لاُسْتَاذِى وَ لِجَمِيعِ الْمُؤْمِنِينَ وَ الْمُؤْمِنَاتِ وَ الْمُسْلِمِينَ وَ الْمُسْلِمَاتِ الْاَحْيَٓاءِ مِنْهُمْ وَ الْاَمْوَاتِ وَ تَرْحَمَنَا رَحْمَةً تُغْنِينَابِهَا عَنْ رَحْمَةِ مَنْ سِوَاكَ مِنْ خَلْقِكَ وَ اَنْ تَقْضِىَ حَوَايِجَنَا وَ تُعْطِيَنَا سُؤَالَنَا فِى الدُّنْيَا وَ اْلاٰخِرَةِ وَ تَخْتِمَ لَنَا بِالسَّعَادَةِ وَ الشَّهَادَةِ وَ الْكَرَامَةِ وَ الْبُشْرٰى عِنْدَ فِرَاقِ الدُّنْيَا وَ تَجْزِىَ مُحَمَّدًا صَلَّى اللّٰهُ عَلَيْهِ وَ سَلَّمَ عَنَّا مَا هُوَ اَهْلُهُ وَ مُسْتَحَقُّهُ●
وَ اَنْ لَا تَكِلَنَا عَلَٓى اَنْفُسِنَا طَرْفَةَ عَيْنٍ وَ لَٓا اِلَٓى اَحَدٍ مِنْ خَلْقِكَ●
وَ تُصْلِحَ لَنَا شَاْنَنَا وَ اَنْ تَحْرُسَنَا بِعَيْنِكَ الَّتِى لَا تَنَامُ وَ تَحْفَظَنَا بِرُكْنِكَ الَّذِى لَا يُرَامُ يَا ذَا الْجَلَالِ وَ اْلاِكْرَامِ●
وَ اَنْ تَصْرِفَ عَنَّا وَ عَمَّنْ عُلِّقَ عَلَيْهِ هٰذِهِ الْاَسْمَٓاءُ اٰفَةَ الْجِنِّ وَ اْلاِنْسِ وَ الشَّيَاطِينِ وَ زَلْزَلَةَ الْاَرْضِ وَ دَكْدَكَةَ الْجِبَالِ مِنْ خَشْيَتِهِ وَ اٰفَةَ الطَّاعُونِ وَ الْوَبَٓاءِ وَ عَيْنَ السُّٓوءِ وَ وَجَعَ الْجَوَارِحِ وَسَٓائِرَ اْلاٰفَاتِ و تَحَفْظَنَا مِنْ كُلِّ شَرٍّ وَ سُٓوءٍ وَ تَرْزُقَنَا السَّلَامَةَ وَ الْعَافِيَةَ وَ الْخَيْرَ فِى الدُّنْيَا وَ اْلاٰخِرَةِ اِنَّكَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ●بِرَحْمَتِكَ يَٓا اَرْحَمَ الرَّاحِمِينَ وَ صَلَّى اللّٰهُ عَلٰى سَيِّدِنَا مُحَمَّدٍ وَ اٰلِهِ وَ صَحْبِهِٓ اَجْمَعِينَ وَ الْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِينَ
`